/*
 * Copyright 2026 Dakkshesh <beakthoven@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package io.github.beakthoven.TrickyStoreOSS.interceptors

import android.system.keystore2.KeyDescriptor
import android.system.keystore2.KeyEntryResponse
import io.github.beakthoven.TrickyStoreOSS.CertificateGen
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/** Phase 6K-FINAL: current target mode authority over historical owners. */
class CurrentModeAuthorityTest {
    private companion object {
        const val UID_A = 10485
        const val UID_B = 10486
        const val ALIAS = "KeyAttestation"
        const val NSPACE = 0x0123456789ABCDEFL
    }

    @Before
    fun setUp() = resetState()

    @After
    fun tearDown() = resetState()

    private fun resetState() {
        CertificateAliasCache.keys.clear()
        CertificateAliasCache.patchedResponses.clear()
        CertificateAliasCache.skipLeafHacks.clear()
        CertificateAliasCache.keysByNspace.clear()
        PassthroughKeyRegistry.clear()
    }

    private fun descriptor(uid: Int = UID_A, alias: String = ALIAS): KeyDescriptor =
        KeyDescriptor().apply {
            domain = 0
            nspace = NSPACE
            this.alias = alias
        }

    private fun seedGenerated(uid: Int = UID_A, alias: String = ALIAS) {
        val k = CertificateAliasCache.Key(uid, alias)
        CertificateAliasCache.keys[k] =
            CertificateAliasCache.Info(
                null,
                null,
                KeyEntryResponse(),
                CertificateGen.KeyGenParameters(emptyArray()),
            )
        CertificateAliasCache.skipLeafHacks[k] = true
        CertificateAliasCache.keysByNspace[NSPACE] = k
    }

    private fun seedPatched(uid: Int = UID_A, alias: String = ALIAS) {
        CertificateAliasCache.patchedResponses[CertificateAliasCache.Key(uid, alias)] = KeyEntryResponse()
    }

    private fun postAction(plainAuto: Boolean, hasGenerated: Boolean, hasPatch: Boolean, tracked: Boolean = false) =
        GetKeyEntryPostPolicy.decide(
            GetKeyEntryPostPolicy.PostHookInput(
                isPassthroughTracked = tracked,
                hasCachedPatch = hasPatch,
                hasGeneratedOwner = hasGenerated,
                explicitLeafHack = false,
                autoPreserveUntrackedReal = plainAuto,
                plainAutoMode = plainAuto,
            ),
        )

    @Test
    fun explicitGenerateOwnerThenAutoGetDoesNotServeGenerated() {
        seedGenerated()
        assertTrue(GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor()))
        assertNull(CertificateAliasCache.findGeneratedKey(UID_A, descriptor()))
        assertEquals(
            GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
            postAction(plainAuto = true, hasGenerated = false, hasPatch = false),
        )
    }

    @Test
    fun explicitPatchOwnerThenAutoGetDoesNotServePatch() {
        seedPatched()
        assertTrue(GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor()))
        assertNull(CertificateAliasCache.resolvePatchedResponse(UID_A, descriptor()))
        assertEquals(
            GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
            postAction(plainAuto = true, hasGenerated = false, hasPatch = false),
        )
    }

    @Test
    fun pre6kBrokenAutoGeneratedOwnerThenNewAutoInvalidates() {
        seedGenerated()
        GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor())
        assertFalse(GetKeyEntryCurrentModeAuthority.shouldServeHistoricalOwner(true, false, false))
        assertEquals(
            GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
            postAction(plainAuto = true, hasGenerated = false, hasPatch = false),
        )
    }

    @Test
    fun autoAfterGeneratedOwnerCallsRealKeystore() {
        seedGenerated()
        assertTrue(GetKeyEntryCurrentModeAuthority.shouldForwardRealKeystore(plainAutoMode = true))
        GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor())
        assertNull(CertificateAliasCache.findGeneratedKey(UID_A, descriptor()))
    }

    @Test
    fun autoAfterPatchedOwnerCallsRealKeystore() {
        seedPatched()
        GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor())
        assertNull(CertificateAliasCache.resolvePatchedResponse(UID_A, descriptor()))
    }

    @Test
    fun autoRealKeyMissingPropagatesFailurePolicy() {
        assertFalse(GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor()))
        assertEquals(
            GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
            postAction(plainAuto = true, hasGenerated = false, hasPatch = false),
        )
    }

    @Test
    fun explicitGenerateStillServesGeneratedOwner() {
        seedGenerated()
        assertEquals(
            GetKeyEntryPostPolicy.Action.SERVE_CACHED_PATCH,
            postAction(plainAuto = false, hasGenerated = true, hasPatch = false),
        )
        assertFalse(GetKeyEntryCurrentModeAuthority.shouldForwardRealKeystore(plainAutoMode = false))
    }

    @Test
    fun explicitLeafStillServesPatchedOwner() {
        seedPatched()
        assertEquals(
            GetKeyEntryPostPolicy.Action.SERVE_CACHED_PATCH,
            postAction(plainAuto = false, hasGenerated = false, hasPatch = true),
        )
    }

    @Test
    fun trackedPassthroughUnaffected() {
        PassthroughKeyRegistry.promote(UID_A, ALIAS, NSPACE)
        seedGenerated()
        assertEquals(
            GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
            postAction(plainAuto = true, hasGenerated = true, hasPatch = false, tracked = true),
        )
    }

    @Test
    fun phase6jUntrackedRealBehaviorUnchangedWithoutHistoricalOwner() {
        assertEquals(
            GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
            postAction(plainAuto = true, hasGenerated = false, hasPatch = false),
        )
        val label =
            TrustClassMapping.forGetKeyEntryPostAction(
                GetKeyEntryPostPolicy.Action.PASSTHROUGH_UNMODIFIED,
                isPassthroughTracked = false,
                plainAutoCurrentMode = true,
            )
        assertEquals(AttestationTrustClass.REAL_KEYSTORE_UNMODIFIED, label.trustClass)
        assertEquals("auto-current-mode-real-response", label.reason)
    }

    @Test
    fun differentUidSameAliasRemainsIsolated() {
        seedGenerated(UID_A, ALIAS)
        assertNull(CertificateAliasCache.findGeneratedKey(UID_B, descriptor(UID_B, ALIAS)))
        assertFalse(GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_B, descriptor(UID_B, ALIAS)))
        assertNotNull(CertificateAliasCache.findGeneratedKey(UID_A, descriptor(UID_A, ALIAS)))
    }

    @Test
    fun reloadedSyntheticOwnerRejectedByAutoAfterSimulatedPersistenceReload() {
        seedGenerated()
        GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor())
        seedGenerated()
        assertTrue(GetKeyEntryCurrentModeAuthority.rejectHistoricalOwners(UID_A, descriptor()))
        assertNull(CertificateAliasCache.findGeneratedKey(UID_A, descriptor()))
    }
}
